// ui/src/routes/proposal/[id].svelte
<script context="module">
  export async function load({ params }) {
    return {
      props: {
        proposalId: params.id
      }
    };
  }
</script>

<script>
  import ProposalDetails from '$components/proposal/ProposalDetails.svelte';

  export let proposalId;
</script>

<div class="py-6">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-6">
    <h1 class="text-2xl font-semibold text-gray-900">Proposal {proposalId}</h1>
  </div>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
    <ProposalDetails {proposalId} />
  </div>
</div>

// client/pages/proposal/[id].tsx
import type { NextPage } from "next";
import { useRouter } from "next/router";

import { ProposalDetail } from "@/components/proposal/ProposalDetail";

const ProposalPage: NextPage = () => {
  const router = useRouter();

  const proposalId = router.query.id;

  return (
    <>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-6">
        <h1 className="text-2xl font-semibold text-gray-900">
          Proposal {proposalId}
        </h1>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
        <ProposalDetail proposalId={proposalId} />
      </div>
    </>
  );
};

export default ProposalPage;
