// ui/src/components/proposal/ProposalPreview.svelte
<script>
  import { goto } from '$app/navigation';

  export let proposal = {};
  export let state = 0;
  export let index = 0;
</script>

<tr
  class={(index % 2 === 0 ? 'bg-white' : 'bg-gray-50') + ' cursor-pointer hover:bg-gray-100'}
  on:click={() => goto(`/proposal/${proposal[0].toString()}`)}
>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    {proposal[0].toString()}
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"> {proposal[1]} </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
    {#if state == 0}
      Pending
    {:else if state == 1}
      Queued
    {:else if state == 2}
      Expired
    {:else if state == 3}
      Executed
    {:else}
      {state} Unknown
    {/if}
  </td>
</tr>

// client/components/proposal/ProposalPreview.tsx
import { useRouter } from "next/router";

export const ProposalPreview = ({ proposal, state, index }) => {
  const router = useRouter();

  return (
    <tr
      className="hover cursor-pointer"
      onClick={() => router.push(`/proposal/${proposal.id}`)}
    >
      <td>{proposal[0].toString()}</td>
      <td>{proposal[1]} </td>
      <td>
        {state == 0 && "Pending"}
        {state == 1 && "Queued"}
        {state == 2 && "Expired"}
        {state == 3 && "Executed"}
      </td>
    </tr>
  );
};
